name: Publish qilletni/postgres

on:
  workflow_dispatch: # For snapshot versions
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qilletni/qilletni:1.0.0

    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/setup-gradle@v5

      - name: Build Package
        run: qilletni build

      - name: QPM Publish
        run: qpm publish
        env:
          QPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: Qilletni/qilletni-package-docs
          event-type: update-docs
          client-payload: '{"package": "postgres"}'
